#pragma once

#include "common.h"

#include <functional>
#include <glm/glm.hpp>
#include <map>
#include <string>
#include <vector>

namespace HopEngine
{

/**
 * @brief static class which provides functionality to tokenise, parse, and process an abstract syntax
 * tree.
 */
class TokenReader final
{
public:
    /**
     * @brief enumerates possible types of outward-facing tokens.
     */
    enum TokenType : uint8_t
    {
        TOKEN_TEXT,
        TOKEN_STRING,
        TOKEN_INT,
        TOKEN_FLOAT,
        TOKEN_VECTOR,
        TOKEN_IDENTIFIER
    };

    /**
     * @brief enumerates all possible types of tokens found in the text representation of the syntax
     * tree. only needed for internal syntax tree parsing, should not be used externally.
     */
    enum TokenTypeInternal : uint8_t
    {
        TOKEN_INTERNAL_TEXT       = TOKEN_TEXT,
        TOKEN_INTERNAL_STRING     = TOKEN_STRING,
        TOKEN_INTERNAL_INT        = TOKEN_INT,
        TOKEN_INTERNAL_FLOAT      = TOKEN_FLOAT,
        TOKEN_INTERNAL_VECTOR     = TOKEN_VECTOR,
        TOKEN_INTERNAL_IDENTIFIER = TOKEN_IDENTIFIER,
        TOKEN_INTERNAL_OPEN_ROUND,
        TOKEN_INTERNAL_CLOSE_ROUND,
        TOKEN_INTERNAL_OPEN_CURLY,
        TOKEN_INTERNAL_CLOSE_CURLY,
        TOKEN_INTERNAL_NEWLINE,
        TOKEN_INTERNAL_COLON,
        TOKEN_INTERNAL_SEMICOLON,
        TOKEN_INTERNAL_COMMA,
        TOKEN_INTERNAL_END_VECTOR,
        TOKEN_INTERNAL_EQUALS,
        TOKEN_INTERNAL_COMMENT,
        TOKEN_INTERNAL_INVALID,
        TOKEN_INTERNAL_WHITESPACE
    };

    /**
     * @brief struct describing a token, or a segment of input text transformed/extracted into a more
     * easily handled form.
     */
    struct Token final
    {
        TokenType type = TOKEN_INT; // type of the token
        union
        {
            glm::vec4 c_value = { 0, 0, 0, 0 }; // coordinate/vector value
            int i_value;                        // integer value
            float f_value;                      // float value
        };
        std::string s_value = ""; // string value
        // offset of the first character of the original token within the original string, used for errors
        size_t start_offset = 0;

        Token() {}

        Token(const TokenType _type) { type = _type; }
        Token(const Token& other);
        Token operator=(const Token& other);
        Token operator=(Token&& other) noexcept;
    };

    /**
     * @brief describes a statement in a parsed syntax tree, consisting of a keyword, series of arguments
     * (which may or may not be named), array of child statements, and an identifier allowing the statement
     * ot be referenced elsewhere.
     */
    struct Statement final
    {
        std::string keyword;    // main instruction defining the statement
        std::string identifier; // identifier tacked onto the end of the statement
        // arguments specified inside brackets after the keyword
        std::vector<std::pair<std::string, Token>> arguments;
        std::vector<Statement> children; // child statements nested inside this one
        // offset of the first character of the statement within the original string, used for errors
        size_t start_offset = 0;
    };

public:
    DELETE_CONSTRUCTORS(TokenReader);

    /**
     * @brief separates a string into a series of internal tokens, with a considerable amount of validation
     * and detailed error reporting. supports arbitrary whitespace and both single and multiline comments
     * via double-slash and slash-star. can be instructed not to emit dead tokens (comments and whitespace)
     * which simplifies downstream syntax parsing.
     * @param content string content to ingest.
     * @param trim_comments if `true`, do not emit comment tokens in the final token array.
     * @param trim_whitespace if `true, do not emit whitespace tokens (space, tab, newline, etc).
     * @returns array of internal tokens (i.e more parsing is required using `extractSyntaxTree`); empty if
     * an error was encountered during parsing.
     */
    static std::vector<Token> tokenise(const std::string& content, bool trim_comments = true,
        bool trim_whitespace = true);
    /**
     * @brief tries to find the closing round brace or curly bracket which matches the given opening
     * bracket. correctly respects nested brackets.
     * @param tokens array of (internal) tokens on which to operate, generated by `tokenise`.
     * @param open_index iterator into `tokens` which points to the opening brace/bracket.
     * @param original_content original text content which was parsed to generate `tokens`, used for error
     * reporting.
     * @returns iterator pointing to the matching closing brace/bracket, or `tokens.end()` if there was no
     * matching brace/bracket.
     */
    static std::vector<Token>::const_iterator findClosingBrace(const std::vector<Token>& tokens,
        const std::vector<Token>::const_iterator open_index, const std::string& original_content);
    /**
     * @brief extracts an abstract syntax tree from an array of internal tokens generated by `tokenise`.
     * performs considerable validation with detailed error reporting. processes an array of `Token`s into
     * an organised series of `Statement`s which can be easily processed by client code to load custom
     * serial formats.
     * @param tokens array of internal tokens on which to operate, generated by `tokenise`.
     * @param original_content original text content which was parsed to generate `tokens`, used for error
     * reporting.
     * @returns array of parsed `Statement` structures; empty if an error was encountered during parsing.
     */
    static std::vector<Statement> extractSyntaxTree(const std::vector<Token>& tokens,
        const std::string& original_content);

    /**
     * @brief converts a `TokenType` into a string representation.
     * @param t `TokenType` to stringify.
     * @returns printable representation of `t`.
     */
    static constexpr std::string typeToString(const TokenType t)
    {
        switch (t)
        {
        case TOKEN_TEXT:       return "keyword";
        case TOKEN_STRING:     return "string";
        case TOKEN_INT:        return "int";
        case TOKEN_FLOAT:      return "float";
        case TOKEN_VECTOR:     return "vector";
        case TOKEN_IDENTIFIER: return "identifier";
        default:               return "unknown";
        }
    }

    /**
     * @brief generates a string highlighting a particular area within another string. used for generating
     * detailed errors in order to explain where an error occurred. extracts a small snipped around the
     * error, quotes the line and column number of the offending text, and points to it. an example of a
     * generated string is below.
     * ```\n  -> '... albedo", resource = @algbedo, filter ...'\n  ->      ^ here (ln 5, col 40)```
     * @param offset start position in `str` to point to.
     * @param str string into which the quote is being directed.
     * @returns printable string summary of where an error (if you're using it for that) occurred.
     */
    static std::string generateError(size_t offset, const std::string& str);

private:
    /**
     * @brief checks if a character is considered alphabetic text.
     * @param c character to check.
     * @returns `true` if `c` is within the ranges of uppercase or lowercase text, or underscore, otherwise
     * `false`.
     */
    static bool isAlphabetic(const char c)
    {
        if (c >= 'a' && c <= 'z') return true;
        if (c >= 'A' && c <= 'Z') return true;
        if (c == '_') return true;
        return false;
    }

    /**
     * @brief checks if an internal token type can be considered a separator between other tokens. for
     * example, `helloworld12345` would be considered a single conjoined token, since there is no separator
     * between the two halves; `helloworld=12345` is considered multiple separate tokens, since the equals
     * functions as a separator token.
     * @param t internal token type to check
     * @returns `true` if the token type is allowed to separate other tokens, or `false` if it will be
     * merged when placed directly next to others.
     */
    static constexpr bool isSeparator(const TokenTypeInternal t)
    {
        switch (t)
        {
        case TOKEN_INTERNAL_TEXT:
        case TOKEN_INTERNAL_STRING:
        case TOKEN_INTERNAL_INT:
        case TOKEN_INTERNAL_IDENTIFIER:
        case TOKEN_INTERNAL_END_VECTOR: return false;
        default:                        return true;
        }
    }

    /**
     * @brief queries the token type of a character. some characters become different types depending on
     * what came before them (such as alphabetic characters following an '@' symbol, which become part of
     * the identifier token), but this function examines the basic type of the character, with contextual
     * processing being carried out by the caller.
     * @param c character to examine.
     * @returns internal token type depending on the character.
     */
    static TokenTypeInternal getType(const char c)
    {
        if (isAlphabetic(c)) return TOKEN_INTERNAL_TEXT;
        if (c == '-' || (c >= '0' && c <= '9')) return TOKEN_INTERNAL_INT;
        switch (c)
        {
        case '@':  return TOKEN_INTERNAL_IDENTIFIER;
        case '(':  return TOKEN_INTERNAL_OPEN_ROUND;
        case ')':  return TOKEN_INTERNAL_CLOSE_ROUND;
        case '{':  return TOKEN_INTERNAL_OPEN_CURLY;
        case '}':  return TOKEN_INTERNAL_CLOSE_CURLY;
        case '\"': return TOKEN_INTERNAL_STRING;
        case '\r':
        case '\n': return TOKEN_INTERNAL_NEWLINE;
        case ':':  return TOKEN_INTERNAL_COLON;
        case '=':  return TOKEN_INTERNAL_EQUALS;
        case ',':  return TOKEN_INTERNAL_COMMA;
        case '[':  return TOKEN_INTERNAL_VECTOR;
        case ']':  return TOKEN_INTERNAL_END_VECTOR;
        case '.':  return TOKEN_INTERNAL_FLOAT;
        case '/':  return TOKEN_INTERNAL_COMMENT;
        case ';':  return TOKEN_INTERNAL_SEMICOLON;
        case ' ':
        case '\t': return TOKEN_INTERNAL_WHITESPACE;
        default:   return TOKEN_INTERNAL_INVALID;
        }
    }

    /**
     * @brief extracts a vector/coordinate token from a string chunk. vector tokens are enclosed in square
     * brackets, and contain comma-separated numerical values (stored as floats) with a minimum of 1
     * component and a maximum of 4.
     * @param str string chunk to extract from.
     * @param offset offset of the start of the string into `original_content`, used for error reporting.
     * @param original_content original text content which is being parsed to generate `tokens`, used for
     * error reporting.
     * @returns vector of floats where at least one component should be initialised, unless an error
     * occurred.
     */
    static glm::vec4 deserialiseVectorToken(const std::string& str, size_t offset,
        const std::string& original_content);
    /**
     * @brief extracts statement arguments between a start and end iterator. performs validation. arguments
     * may be anonymous (unnamed, with a single argument consisting of a single value token), or named
     * (with a text identifier, an equals, and then a single value token). value tokens may be
     * `TOKEN_STRING`, `TOKEN_TEXT`, `TOKEN_IDENTIFIER`, `TOKEN_FLOAT`, `TOKEN_INT`, or `TOKEN_VECTOR`.
     * @param start iterator pointing to the open bracket token before arguments begin.
     * @param end iterator pointing to the close bracket token after arguments end.
     * @returns array of pairs, where the first of each is the name of the argument (empty if the argument
     * was anonymous), and the second is the value token.
     */
    static std::vector<std::pair<std::string, Token>> parseArguments(
        std::vector<Token>::const_iterator start, std::vector<Token>::const_iterator end,
        const std::string& original_content);

    /**
     * @brief reports an error to the console. includes information about where in the input string the
     * error occurred.
     * @param err string describing the error.
     * @param off offset of the first character of the error-causing text.
     * @param str original text for which the error is being emitted.
     * @returns SIZE_MAX.
     */
    static size_t reportError(const std::string& err, size_t off, const std::string& str);
};

class Deserialiser final
{
public:
    enum StatementIdentifierStatus
    {
        STATEMENT_IDENTIFIER_FORBIDDEN,
        STATEMENT_IDENTIFIER_OPTIONAL,
        STATEMENT_IDENTIFIER_REQUIRED
    };

    struct StatementSpec
    {
        std::string keyword_name;
        StatementIdentifierStatus identifier_allowed;
        bool children_permitted;

        StatementSpec(std::string keyword, StatementIdentifierStatus identifier, bool children) :
            keyword_name(keyword), identifier_allowed(identifier), children_permitted(children)
        {
        }
        StatementSpec() :
            keyword_name(""), identifier_allowed(STATEMENT_IDENTIFIER_OPTIONAL), children_permitted(true)
        {
        }
    };

    struct AnonymousStatementSpec final : public StatementSpec
    {
        std::vector<TokenReader::TokenType> expected_anon_args;

        using StatementSpec::StatementSpec;
        AnonymousStatementSpec& argument(TokenReader::TokenType type)
        {
            expected_anon_args.push_back(type);
            return *this;
        }
    };

    struct NamedStatementSpec final : public StatementSpec
    {
        std::map<std::string, std::pair<TokenReader::TokenType, bool>> expected_named_args;

        using StatementSpec::StatementSpec;
        NamedStatementSpec& argument(std::string name, TokenReader::TokenType type, bool required)
        {
            expected_named_args[name] = { type, required };
            return *this;
        }
    };

    struct AnonymousStatementResult
    {
        TokenReader::Statement statement;
        std::vector<TokenReader::Token> arguments;

        size_t offsetOf(size_t index);
        void read(size_t index, float& destination) const;
        void read(size_t index, int& destination) const;
        void read(size_t index, uint32_t& destination) const;
        void read(size_t index, glm::vec2& destination) const;
        void read(size_t index, glm::ivec2& destination) const;
        void read(size_t index, glm::vec3& destination) const;
        void read(size_t index, glm::ivec3& destination) const;
        void read(size_t index, glm::vec4& destination) const;
        void read(size_t index, std::string& destination) const;
        bool read(size_t index, bool& destination) const;
        template<typename T>
        bool read(size_t index, T& destination, std::function<bool(const std::string&, T&)> converter) const
        { return converter(arguments[index].s_value, destination); }
    };

    struct NamedStatementResult
    {
        TokenReader::Statement statement;
        std::map<std::string, TokenReader::Token> arguments;

        size_t offsetOf(const std::string& name);
        void read(const std::string& name, float& destination) const;
        void read(const std::string& name, int& destination) const;
        void read(const std::string& name, uint32_t& destination) const;
        void read(const std::string& name, glm::vec2& destination) const;
        void read(const std::string& name, glm::ivec2& destination) const;
        void read(const std::string& name, glm::vec3& destination) const;
        void read(const std::string& name, glm::ivec3& destination) const;
        void read(const std::string& name, glm::vec4& destination) const;
        void read(const std::string& name, std::string& destination) const;
        bool read(const std::string& name, bool& destination) const;
        template<typename T> bool read(const std::string& name, T& destination,
            std::function<bool(const std::string&, T&)> converter) const
        {
            std::string data;
            read(name, data);
            if (data.empty()) return true;
            else
                return converter(data, destination);
        }
    };

private:
    std::map<std::string, std::pair<AnonymousStatementSpec, std::function<bool(AnonymousStatementResult)>>>
        anonymous_statement_types;
    std::map<std::string, std::pair<NamedStatementSpec, std::function<bool(NamedStatementResult)>>>
        named_statement_types;

    std::string error;

public:
    DELETE_CONSTRUCTORS(Deserialiser);
    Deserialiser(std::string error_base) : error(error_base) {}
    ~Deserialiser() = default;

    void addStatementAnonymous(const AnonymousStatementSpec& spec,
        std::function<bool(AnonymousStatementResult)> handler)
    { anonymous_statement_types[spec.keyword_name] = { spec, handler }; }
    void addStatementNamed(const NamedStatementSpec& spec,
        std::function<bool(NamedStatementResult)> handler)
    { named_statement_types[spec.keyword_name] = { spec, handler }; }

    bool execute(const std::vector<TokenReader::Statement>& statements, const std::string& token_str);
    bool emitError(const std::string& error);
    bool emitError(const std::string& error, size_t offset, const std::string& token_str);

private:
    bool errorCheckAnonymous(const TokenReader::Statement& statement, const AnonymousStatementSpec& spec,
        std::vector<TokenReader::Token>& output, const std::string& token_str);
    bool errorCheckNamed(const TokenReader::Statement& statement, const NamedStatementSpec& spec,
        std::map<std::string, TokenReader::Token>& output, const std::string& token_str);
};

} // namespace HopEngine
